---
# NOTE - the OpenVPN RPM contains units for openvpn-client and openvpn-server
# but these don't appear to be usable on first go.


- name: save iptables
  shell: "iptables-save > /etc/iptables/rules.v4"
  become: true
  changed_when: false
  notify: reload iptables

- name: reload iptables
  iptables: # this is the new stuff
    state: reload

- name: restart openvpn server
  service:
    name: "openvpn@{{ inventory_hostname }}.service"
    enabled: yes
    state: restarted

- name: restart openvpn clients
  service:
    name: "openvpn@{{ item }}.service"
    enabled: yes
    state: restarted
  with_items: "{{ openvpn_servers | difference([inventory_hostname]) }}"
...
