- hosts:
    - openvpn_clients
  become: true
  tasks:
   - name: Purge OpenVPN
     package:
       name: openvpn
       state: absent

   - name: remove /etc/openvpn
     file:
       path: /etc/openvpn
       state: absent 
