---
- hosts:
   - localhost
  vars:
    external_ingress_nodes: []
  gather_facts: no
  pre_tasks:
    - set_fact:
        external_ingress_nodes: "{{ external_ingress_nodes + [hostvars[item]['ec2_private_dns_name']] }} "
      with_items: " {{ groups['tag_role_k3os_ingress'] }} "

  roles:
    - role: node-label
      node_group: "{{ groups['workers'] }}"
      kube_labels:
        node-role.kubernetes.io/worker: ""

    - role: node-label
      node_group: "{{ groups['storage'] }}"
      kube_labels:
        node-role.kubernetes.io/storage: ""

    - role: node-label
      node_group: "{{ groups['ingress-internal'] }}"
      kube_labels:
        node-role.kubernetes.io/ingress-internal: ""

    - role: node-label
      node_group: "{{ external_ingress_nodes }}"
      kube_labels:
        node-role.kubernetes.io/ingress-external: ""

    - role: node-label
      node_group: "{{ groups['climate'] }}"
      kube_labels:
        node-role.kubernetes.io/climate: ""

    - role: node-label
      node_group: "{{ groups['camera'] }}"
      kube_labels:
        node-role.kubernetes.io/camera: ""
