---
# Idempotency:
# Extract CIDRs for all routes currently configured on all play hosts
- name: Extract routes from system route table
  command: /usr/sbin/ip route
  changed_when: false
  register: routes
- name: Convert route CIDRs to facts
  set_fact:
    cidr: "{{ item.split() | first }}"
  with_items: "{{ routes.stdout_lines }}"
  register: cidrs_reg
- name: Canonicalise route CIDR fact structure
  set_fact:
    route_cidrs: "{{ cidrs_reg.results | map(attribute='ansible_facts.cidr') | list | ipv4 | ipaddr('net') }}"

# The list of all subnets for which this host must add a route
- name: Find VPN remote subnets
  set_fact:
    vpn_cidr: "{{ vpn_netmask | ipaddr('net') }}"
  vars:
    vpn_netmask: "{{ hostvars[item]['openvpn_intra_ipv4']['network'] }}/{{ hostvars[item]['openvpn_intra_ipv4']['netmask'] }}"
  with_items: "{{ openvpn_servers + openvpn_clients }}"
  register: vpn_cidrs_reg
- name: Canonicalise and filter remote subnet fact structure
  set_fact:
    vpn_cidrs: "{{ vpn_cidrs_reg.results | map(attribute='ansible_facts.vpn_cidr') | list | difference(route_cidrs) }}"

# Find the local VPN client / gateway router
- name: Find our local VPN client gateway router
  set_fact:
    local_vpn_gw: "{{ hostvars[item]['openvpn_intra_ipv4']['address'] }}"
  when:
    - hostvars[item].openvpn_intra_ipv4.network == openvpn_intra_ipv4.network
  with_items: "{{ openvpn_servers + openvpn_clients }}"

# Apply the route ephmerally
- name: Assign routes to remote networks via VPN client gateways
  command:  "/usr/sbin/ip route add {{ item }} via {{ local_vpn_gw }} dev {{ openvpn_intra_if }}"
  become: true
  with_items: "{{ vpn_cidrs }}"
  when:
    - inventory_hostname != local_vpn_gw

# Apply the route persistently (CentOS/Red Hat)
- name: Define persistent routes to remote networks
  lineinfile:
    line: "{{ item }} via {{ local_vpn_gw }} dev {{ openvpn_intra_if }}"
    path: "/etc/sysconfig/network-scripts/route-{{ openvpn_intra_if }}"
    create: yes
    owner: root
    group: root
    mode: 0755
  become: true
  with_items: "{{ vpn_cidrs }}"
  when:
    - inventory_hostname != local_vpn_gw

...
